apiVersion: apps/v1
kind: Deployment
metadata:
  name: "meudeployment"
  labels:
    app: "meudeployment"
spec:
  selector:
    matchLabels:
      app: meudeployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: meudeployment
    spec:
      containers:
        - name: meudeployment
          image:  gabrielguimaraesdvlpr/trick-api:v1.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100M
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: meudeployment
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret